### ISSUE TITLE
Warning from Vercel AI SDK: Slow UI updates with certain models

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#1]
The AI SDK is displaying a warning message: `The streamable UI has been slow to update. This may be a bug or a performance issue or you forgot to call .done().` 

However, this warning does not appear when using faster models like gpt-3.5-turbo, suggesting that the issue is not related to missing .done() calls. The problem seems to be on the SDK side, although further research is needed to confirm the root cause. This issue is being created to document the warning as a known issue, making it visible to other developers. More investigation will be required to identify the underlying problem and find a suitable solution.

**Comment by lgrammel** [comment]
I think this only shows in dev mode. You can ignore it if you know it's the model speed:

https://github.com/vercel/ai/blob/main/packages/core/rsc/streamable.tsx#L36

**Comment by miurla** [comment]
@lgrammel 

Thank you for your comment!
Understood. I'm relieved if it's okay to ignore it. It seems like it would inevitably occur when streaming agents or other long-running processes.
