### ISSUE TITLE
Application error: a client-side exception has occurred

### ISSUE THREAD

**Issue by 0smboy** [miurla/morphic#10]
When I search in Chinese for "周杰伦是谁？" I get the following question
<img width="1521" alt="image" src="https://github.com/miurla/morphic/assets/91452062/9fb8b794-3f5c-447e-b454-f82ca04bf32e">

**Comment by Adarshagupta** [comment]
Same Problem. With all language

**Comment by onlinedear** [comment]
确实存在这个问题 希望能修复这个bug
此外希望一键部署的Velcal自定义参数字段里，支持openai代理地址的填写

**Comment by onlinedear** [comment]
![微信图片_20240411131519](https://github.com/miurla/morphic/assets/10751712/0e8ad915-e06a-4cfb-a80e-cd5742ef7dfa)

**Comment by miurla** [comment]
@0smboy 

I tried the phrase "周杰伦是谁？" several times in morphic.sh, but I couldn't reproduce the issue. Please provide the following three points of information:

1. In which environment did the issue occur?
   1. Your local environment
   2. Your hosting
2. Does it occur in morphic.sh?
3. At what point does the crash occur?
4. How frequently does the issue occur?

**Comment by onlinedear** [comment]
> @0smboy
> 
> I tried the phrase "周杰伦是谁？" several times in morphic.sh, but I couldn't reproduce the issue. Please provide the following three points of information:
> 
> 1. In which environment did the issue occur?
>    
>    1. Your local environment
>    2. Your hosting
>    3. Did you change the OpenAI model?
> 2. Does it occur in morphic.sh?
> 3. At what point does the crash occur?
> 4. How frequently does the issue occur?

Demo：
https://morphic-blond.vercel.app/     

This is an environment deployed through Vercel with one-click deployment. During the deployment process, I filled in both OPENAI_API_KEY and TAVILY_API_KEY. The error message above appears regardless of whether a domain is bound or not.

**Comment by miurla** [comment]
@onlinedear 

Thank you for sharing the preview URL.
I was able to confirm the reproduction of the issue.
(Please remove the preview URL from the comments, as it is publicly accessible)

Could you please provide the error logs from the Logs tab on the Vercel dashboard?

**Comment by onlinedear** [comment]
Here are the steps I took:
Step 1: I opened the GitHub address of this project and clicked "Deploy" - Host your own live version of Morphic with Vercel.
Step 2: After entering Vercel, I entered the project name.
Step 3: I input OPENAI_API_KEY and TAVILY_API_KEY.
Step 4: Wait and complete the deployment.
Step 5: Access the domain name assigned by the system, https://morphic-blond.vercel.app/
Step 6: I can access the home page of the deployed project and enter a question.
Step 7: An error occurred.
Step 8: Tried to bind a domain name, but the problem still exists.

**Comment by onlinedear** [comment]
I hope to have the option to fill in the proxy address before entering the OPENAI_API_KEY parameter on Vercel.

**Comment by miurla** [comment]
@onlinedear 

> Could you please provide the error logs from the Logs tab on the Vercel dashboard?

**Comment by onlinedear** [comment]
` AI_RetryError: Failed after 3 attemps. Last error: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at (node_modules/ai/dist/index.mjs:670:0)
    at (node_modules/ai/dist/index.mjs:791:0)
    at (lib/agents/task-manager.tsx:7:17)
    at (app/action.tsx:43:24) {
  name: 'AI_RetryError',
  reason: 'maxRetriesExceeded',
  errors: [
   AI_APICallError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at (node_modules/ai/openai/dist/index.mjs:448:0)
    at (node_modules/ai/openai/dist/index.mjs:340:0)
    at (node_modules/ai/openai/dist/index.mjs:776:0)
    at (node_modules/ai/dist/index.mjs:658:0)
    at (node_modules/ai/dist/index.mjs:791:0)
    at (lib/agents/task-manager.tsx:7:17)
    at (app/action.tsx:43:24) {
  name: 'AI_APICallError',
  url: 'https://api.openai.com/v1/chat/completions',
  requestBodyValues: {
  model: 'gpt-3.5-turbo',
  logit_bias: undefined,
  user: undefined,
  max_tokens: undefined,
  temperature: undefined,
  top_p: undefined,
  frequency_penalty: undefined,
  presence_penalty: undefined,
  seed: undefined,
  messages: [
  {
  role: 'system',
  content: 'As a professional web researcher, your primary objective is to fully comprehend the user\'s query, conduct thorough web searches to gather the necessary information, and provide an appropriate response.\n    To achieve this, you must first analyze the user\'s input and determine the optimal course of action. You have two options at your disposal:\n    1. "proceed": If the provided information is sufficient to address the query effectively, choose this option to proceed with the research and formulate a response.\n    2. "inquire": If you believe that additional information from the user would enhance your ability to provide a comprehensive response, select this option. You may present a form to the user, offering default selections or free-form input fields, to gather the required details.\n    Your decision should be based on a careful assessment of the context and the potential for further information to improve the quality and relevance of your response.\n    For example, if the user asks, "What are the key features of the latest iPhone model?", you may choose to "proceed" as the query is clear and can be answered effectively with web research alone.\n    However, if the user asks, "What\'s the best smartphone for my needs?", you may opt to "inquire" and present a form asking about their specific requirements, budget, and preferred features to provide a more tailored recommendation.\n    Make your choice wisely to ensure that you fulfill your mission as a web researcher effectively and deliver the most valuable assistance to the user.\n    '
},
  {
  role: 'user',
  content: [
  { type: 'text', text: '{"input":"Why is Nvidia growing rapidly?"}' }
]
}
],
  tool_choice: { type: 'function', function: { name: 'json' } },
  tools: [
  {
  type: 'function',
  function: {
  type: 'function',
  name: 'json',
  description: 'Respond with a JSON object.',
  parameters: {
  type: 'object',
  properties: { next: { type: 'string', enum: [ 'inquire', 'proceed' ] } },
  required: [ 'next' ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#'
}
}
}
]
},
  statusCode: 429,
  responseBody: '{\n    "error": {\n        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",\n        "type": "insufficient_quota",\n        "param": null,\n        "code": "insufficient_quota"\n    }\n}\n',
  cause: undefined,
  isRetryable: true,
  data: {
  error: {
  message: 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
  type: 'insufficient_quota',
  param: null,
  c`

**Comment by onlinedear** [comment]
It seems that this error is due to insufficient quota for my account. Can you support Azure's API?

**Comment by onlinedear** [comment]
I hope to be able to fill in `OPENAI_API_BASE=` in the custom parameters on Vercel, and it would be great if Azure's API was supported.

**Comment by miurla** [comment]
> It seems that this error is due to insufficient quota for my account

🫠

> Can you support Azure's API?

https://github.com/miurla/morphic/issues/13

**Comment by miurla** [comment]
@0smboy @Adarshagupta 

Could you please provide the error logs from the Logs tab on the Vercel dashboard?
If it is an account issue, this issue will be closed

**Comment by onlinedear** [comment]
I hope to be able to fill in OPENAI_API_BASE= in the custom parameters on Vercel,

**Comment by miurla** [comment]
> I hope to be able to fill in OPENAI_API_BASE= in the custom parameters on Vercel,

The contributors have already addressed this. 
- https://github.com/miurla/morphic/pull/22 
- https://github.com/miurla/morphic

Unrelated matters should be commented on in a separate issue.
Otherwise, it becomes difficult to track the problem.

**Comment by onlinedear** [comment]
> > 我希望能够在Vercel上的自定义参数中填写OPENAI_API_BASE=，
> 
> 贡献者已经解决了这个问题。
> 
> * [将metadataBase URL 添加到元数据 #22](https://github.com/miurla/morphic/pull/22)
> * https://github.com/miurla/morphic
> 
> 不相关的事项应在单独的问题中发表评论。 否则，很难跟踪问题。

Thank you very much for sharing such a great project, and also for your patient answers. I hope the project continues to improve and thrive.

**Comment by Linon419** [comment]
When I encountered the same error, I found that the project was using the gpt-4 module.
` AI_APICallError: An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_uelZfMXmhZebZXcncc5vwE7s (request id: 202404120733282053438695TItDXJa)
    at (node_modules/ai/openai/dist/index.mjs:448:0)
    at (node_modules/ai/openai/dist/index.mjs:340:0)
    at (node_modules/ai/openai/dist/index.mjs:807:0)
    at (node_modules/ai/dist/index.mjs:658:0)
    at (node_modules/ai/dist/index.mjs:1352:0)
    at (lib/agents/query-suggestor.tsx:24:2)
    at (app/action.tsx:69:4) {
  name: 'AI_APICallError',
  url: 'https://xxx.xxx/v1/chat/completions',
  requestBodyValues: {
  model: 'gpt-4-turbo-preview',
  logit_bias: undefined,
  user: undefined,
  max_tokens: undefined,
  temperature: undefined,
  top_p: undefined,
  frequency_penalty: undefined,
  presence_penalty: undefined,
  seed: undefined,
  messages: [
  {
  role: 'system',
  content: 'As a professional web researcher, your task is to generate a set of three queries that explore the subject matter more deeply, building upon the initial query and the information uncovered in its search results.\n\n    For instance, if the original query was "Starship\'s third test flight key milestones", your output should follow this format:\n\n    "{\n      "related": [\n        "What were the primary objectives achieved during Starship\'s third test flight?",\n        "What factors contributed to the ultimate outcome of Starship\'s third test flight?",\n        "How will the results of the third test flight influence SpaceX\'s future development plans for Starship?"\n      ]\n    }"\n\n    Aim to create queries that progressively delve into more specific aspects, implications, or adjacent topics related to the initial query. The goal is to anticipate the user\'s potential information needs and guide them towards a more comprehensive understanding of the subject matter.\n    '
},
  {
  role: 'user',
  content: [ { type: 'text', text: '{"input":"周杰伦是谁"}' } ]
},
  {
  role: 'assistant',
  content: '\nError occurred while executing the tool',
  tool_calls: [
  {
  id: 'call_uelZfMXmhZebZXcncc5vwE7s',
  type: 'function',
  function: {
  name: 'search',
  arguments: '{"query":"周杰伦","max_results":5,"search_depth":"basic"}'
}
}
]
}
],
  tool_choice: { type: 'function', function: { name: 'json' } },
  tools: [
  {
  type: 'function',
  function: {
  type: 'function',
  name: 'json',
  description: 'Respond with a JSON object.',
  parameters: {
  type: 'object',
  properties: {
  items: {
  type: 'array',
  items: {
  type: 'object',
  properties: { query: { type: 'string' } },
  required: [ 'query' ],
  additionalProperties: false
},
  minItems: 3,
  maxItems: 3
}
},
  required: [ 'items' ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#'
}
}
}
],
  stream: true
},
  statusCode: 400,
  responseBody: '{"error":{"message":"An assistant message with \'tool_calls\' must be followed by tool messages responding to each \'tool_call_id\'. The following tool_call_ids did not have response messages: call_uelZfMXmhZebZXcncc5vwE7s (request id: 202404120733282053438695TItDXJa)","type":"invalid_request_error","param":"messages","code":null}}',
  cause: undefined,
  isRetryable: false,
  data: {
  error: {
  message: 'An assistant message with \'tool_calls\' must be followed by tool messages responding to each \'tool_call_id\'. The following tool_call_ids did not have response messages: call_uelZfMXmhZebZXcncc5vwE7s (request id: 202404120733282053438695TItDXJa)',
  type: 'invalid_request_error',
  param: 'messages',
  code: null
}
}
}`

**Comment by miurla** [comment]
> `at (app/action.tsx:69:4) {
name: 'AI_APICallError',
url: 'https://xxx.xxx/v1/chat/completions',
requestBodyValues: {
model: 'gpt-4-turbo-preview',`

The URL for `OPENAI_API_BASE` seems to be incorrect.

**Comment by Linon419** [comment]
> > `at (app/action.tsx:69:4) { name: 'AI_APICallError', url: 'https://xxx.xxx/v1/chat/completions', requestBodyValues: { model: 'gpt-4-turbo-preview',`
> 
> The URL for `OPENAI_API_BASE` seems to be incorrect.

The URL in my environment is current. I replace it to xxx to arouse suspicion of advertising.

**Comment by miurla** [comment]
Ah, Okay. The search seems to have failed.
Are you sure you entered the correct value for `TAVILY_API_KEY`?

**Comment by Linon419** [comment]
> Ah, Okay. The search seems to have failed. Are you sure you entered the correct value for `TAVILY_API_KEY`?

Yes, all API keys are correct

**Comment by miurla** [comment]
I fixed to fill with spaces because an error occurs if the query parameter of the Tavily Search API is less than 5 characters.
Your search query `美国加息` was 4 characters long.  
#28 

Please use the latest code and try again.

<img width="740" alt="Screenshot 2024-04-13 at 5 22 20" src="https://github.com/miurla/morphic/assets/3412179/13e44a45-f240-4684-a8b2-04553dc8ec54">
