### ISSUE TITLE
We really need a user login feature similar to morphic.sh.

### ISSUE THREAD

**Issue by aaronpeng2020** [miurla/morphic#107]
Thank you for your efforts. 
The user login and save user record functions are very important. 
I hope you can consider this. 

If possible, please provide a Buy a Coffee link or other sponsorship methods.

**Comment by aaronpeng2020** [comment]
When I deployed this version online, the search history of all users who used the search function was saved, including everyone's search history, due to the lack of user management.

**Comment by aaronpeng2020** [comment]
And if a search is unsuccessful, it displays a blank page, and the blank result gets cached.

**Comment by miurla** [comment]
We don't plan to add authentication.
reason: https://github.com/miurla/morphic?tab=readme-ov-file#morphic
