### ISSUE TITLE
Provide local Redis option

### ISSUE THREAD

**Issue by arsaboo** [miurla/morphic#110]
I don't know why we need to rely on Upstash. We can have a local Redis option.

**Comment by miurla** [comment]
My choice is driven by the ease of build and deployment processes.
https://github.com/miurla/morphic?tab=readme-ov-file#-deploy

Having local Redis as an additional option is acceptable.

**Comment by arsaboo** [comment]
Thanks...I look forward to that option.

**Comment by miurla** [comment]
PR: https://github.com/miurla/morphic/pull/303
