### ISSUE TITLE
cloudflare部署出现：没有配置为在 Cloudflare 的 Edge Runtime 上运行错误

### ISSUE THREAD

**Issue by yxmnjxzx** [miurla/morphic#127]
错误的提示：
<html>
<body>

13:46:29.560 | ⚡️ ERROR: Failed to produce a Cloudflare Pages build from the project.
-- | --
13:46:29.561 | ⚡️
13:46:29.561 | ⚡️ 	The following routes were not configured to run with the Edge Runtime:
13:46:29.561 | ⚡️ 	  - /_not-found
13:46:29.561 | ⚡️ 	  - /index
13:46:29.561 | ⚡️ 	  - /search/[id]
13:46:29.561 | ⚡️
13:46:29.561 | ⚡️ 	Please make sure that all your non-static routes export the following edge runtime route segment config:
13:46:29.562 | ⚡️ 	  export const runtime = 'edge';

</body>
</html>

**Comment by miurla** [comment]
Please check this issue:  https://github.com/miurla/morphic/issues/114
