### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by TheodorosGalanos** [miurla/morphic#13]
Would it be very difficult to add azure openai support to the package?

**Comment by miurla** [comment]
The Azure OpenAI Provider is currently not included in the AI Core Provider, so a custom provider needs to be implemented:

https://sdk.vercel.ai/docs/ai-core/custom-provider


There is also a possibility that it’ll be supported on the SDK side.

**Comment by Beckjiang** [comment]
https://sdk.vercel.ai/docs/guides/providers/azure-openai

It seems that it is already supported.

**Comment by miurla** [comment]
https://sdk.vercel.ai/docs/ai-core

The ai core provider is not supported.

**Comment by miurla** [comment]
https://sdk.vercel.ai/providers/ai-sdk-providers/azure

Supported in the latest version.

**Comment by SzilvasiPeter** [comment]
I can take over this issue, it seems a very small adaptation at the `lib/utils/index.ts` file.

**Comment by istrategy** [comment]
Thank you.[SzilvasiPeter](https://github.com/SzilvasiPeter) Please fix!
