### ISSUE TITLE
Using StreamUI

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#130]
Try to simplify the code by applying it to Researcher

https://sdk.vercel.ai/docs/reference/ai-sdk-rsc/stream-ui

**Comment by Nil2000** [comment]
Hi @miurla Do you want to use streamUI instead of streamText like this?
![image](https://github.com/miurla/morphic/assets/54113952/1a46ffad-c142-4e9a-9cd4-c34b46c7dfc4)

**Comment by miurla** [comment]
Yes. When using `render`, the streamed text couldn't be displayed smoothly. If it's not a problem, it would be better to use `streamUI`.

If it's usable, since a writer has been added, we need to branch with `USE_SPECIFIC_API_FOR_WRITER`.

**Comment by miurla** [comment]
I'm working on this now.

**Comment by miurla** [comment]
I tried streamUI, and while it's convenient for making single tool calls, it wasn't suitable for replacing the researcher, so no replacement was made. Instead, refactoring was carried out. #148
