### ISSUE TITLE
messages with role 'tool' must be a response to a preceeding message with 'tool_calls'

### ISSUE THREAD

**Issue by superlbr** [miurla/morphic#136]
in researcher.tsx
`{"error":{"message":"Invalid parameter: messages with role 'tool' must be a response to a preceeding message with 'tool_calls'. (request id: 2024051116100984850589317176109) (request id: 2024051116100973706982837582869) (request id: 202405111610097110056956WoKcYSs) (request id: 20240511161006903012458ab9obA9U)","type":"invalid_request_error","param":"messages.[3].role","code":null}}`

**Comment by miurla** [comment]
This error occurs when it’s not properly called by the tool. Are you experiencing this without making any changes to the code? Please describe the steps to reproduce.

**Comment by superlbr** [comment]
use model gpt-4 is ok. gpt-4-turbo sometimes error.
just add images and answers in research
