### ISSUE TITLE
LaTeX Support please

### ISSUE THREAD

**Issue by smcmackin20** [miurla/morphic#147]
Everytime I do a math problem Morphic does not support LaTeX and the formatting is broken, please consider adding it
Formating is broken like in the image
![image](https://github.com/miurla/morphic/assets/96853437/7c2435fc-311d-4e2b-a721-49588c51631e)

**Comment by miurla** [comment]
Ask Morphic: How to support LaTeX in react markdown?
https://www.morphic.sh/share/q4B7lln
