### ISSUE TITLE
Model name in speed and quality modes.

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#151]
Hi, I think the speed and quality modes should say the name of the model being used, for example, GPT-4o for the quality mode, and whatever it is for the speed mode. Just like the lightning modes that say llama 3 8b and 70b. Please do this, if you can 🙂 
![Screenshot_20240515_002721_Chrome~2.jpg](https://github.com/miurla/morphic/assets/168287279/ae66ca39-2b94-4897-a481-952fec6982fe)

**Comment by miurla** [comment]
As gpt-4-turbo(Quality) was available for free, there were multiple unauthorized accesses. To prevent such incidents, I didn't mention it explicitly. Now that ChatGPT's gpt-4o has become free, it might be okay to state it. I’ll consider it.

**Comment by walbercardoso** [comment]
> As gpt-4-turbo(Quality) was available for free, there were multiple unauthorized accesses. To prevent such incidents, I didn't mention it explicitly. Now that ChatGPT's gpt-4o has become free, it might be okay to state it. I’ll consider it.

Free? What did you mean?

**Comment by miurla** [comment]
This issue is not about this repo, but rather about the `morphic.sh` website.
It means that on this site, as long as you have an account, you can use Quality mode for free.

**Comment by miurla** [comment]
I have made the change.
However, please understand that there may be a possibility of further changes due to service-related circumstances, as mentioned in the above comment.

<img width="363" alt="image" src="https://github.com/miurla/morphic/assets/3412179/8e40f0a5-ba61-459a-8ac1-229da60ba4a9">

**Comment by ZainGithub12** [comment]
I understand, and thank you.
