### ISSUE TITLE
Support Google Generative AI Provider

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#156]
**Is your feature request related to a problem? Please describe.**
Unable to support models other than OpenAI

**Describe the solution you'd like**
Gemini seems to meet all the requirements

**Describe alternatives you've considered**
Anthropic also meets the requirements

**Additional context**
https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai#model-capabilities

**Comment by freedomtrain** [comment]
Would it be possible to support https://mistral.ai/?

**Comment by miurla** [comment]
Since Model Capabilities is also checked, support is possible.

https://sdk.vercel.ai/providers/ai-sdk-providers/mistral

**Comment by miurla** [comment]
I tried it, but some agents are encountering errors.

**query-suggestor**

`APICallError [AI_APICallError]: Function calling with a response mime type: 'application/json' is unsupported`

**researcher**

`APICallError [AI_APICallError]: Invalid JSON payload received. Unknown name "maximum" at 'tools.function_declarations[0].parameters.properties[1].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[0].parameters.properties[1].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[0].parameters.properties[2].value': Cannot find field.`

**Comment by freedomtrain** [comment]
Thank you for trying !

**Comment by miurla** [comment]
The gemini-1.5-pro and gemini-1.5-flash models have gone GA, so they were tested again. An error occurs with tool use.

```
Error: Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[0].parameters.properties[1].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[0].parameters.properties[2].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[2].parameters.properties[1].value': Cannot find field.
Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[2].parameters.properties[2].value': Cannot find field. [] true
```

There is no issue when running a simple sample with the google provider. Since the tool use is set directly in researcher, it seems necessary to fix that.

**Comment by miurla** [comment]
`Error: Invalid JSON payload received. Unknown name "default" at 'tools.function_declarations[0].parameters.properties[1].value': Cannot find field.`

This error was resolved by modifying the schema. 

However, the following error occurs.

query-suggestor

`APICallError [AI_APICallError]: Function calling with a response mime type: 'application/json' is unsupported`

**Comment by freedomtrain** [comment]
it is now possible to support https://mistral.ai/
