### ISSUE TITLE
Latest YouTube videos

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#168]
Describe the issue:
When I ask for latest YouTube video, e.g. latest Faze Rug video or any other youtuber, the result sometimes outputs an older video rather than the latest.

**Comment by arsaboo** [comment]
I don't think this is a Morphic problem. The underlying search engine may not have scraped the latest content.

**Comment by ZainGithub12** [comment]
Oh okay, maybe you're right :) can this issue be fixed in any way or not then?

**Comment by miurla** [comment]
The video search API we are currently using does not have a date parameter. Even if `latest` is included in the query, if the newest videos are not retrieved, the current API cannot handle it. We need to switch to a different API.

**Comment by ZainGithub12** [comment]
Okay, the same happens with other AI too e.g. Microsoft Copilot, so I understand if it's difficult to find the right API I guess.
