### ISSUE TITLE
Edit customized search engine

### ISSUE THREAD

**Issue by zhl111** [miurla/morphic#182]
### Feature Description

How should I set it up so that it works properly?
![image](https://github.com/miurla/morphic/assets/29135984/28034523-058c-426a-96b8-38fc7b2adca1)

### Use Case

like this
![image](https://github.com/miurla/morphic/assets/29135984/1d381f4f-1a60-44e1-97ca-f1cf23de6c0f)

### Additional context

How should I set it up so that it works properly?

**Comment by Iron56716** [comment]
+1

**Comment by miurla** [comment]
Support completed: #194 
The steps are here: https://github.com/miurla/morphic?tab=readme-ov-file#-search-engine
