### ISSUE TITLE
Provide local Search API option

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#196]
### Feature Description

As an alternative to the Tavily search API, use SearcXNG to provide a local search API. Since SearcXNG returns meta-search results, make it usable from LLM by embedding.

### Use Case

Use it as an option for the search API when launching locally. It has advantages in terms of cost and privacy.

### Additional context

refs: #34 #175

**Comment by GobDevv** [comment]
https://github.com/Snazzah/duck-duck-scrape

Possibly DDG support?

**Comment by ngoiyaeric** [comment]
Recently tried to get data from this endpoint and our current search providers returned an error: 
The site is accessible but does not have https so it gets flagged as unsafe. 

<img width="548" alt="Screen Shot 2024-07-11 at 10 53 15 AM" src="https://github.com/miurla/morphic/assets/115367894/d8fe9eb2-c6d0-475a-852f-abb095736eeb">

**Comment by ngoiyaeric** [comment]
Would be great to have control all the way down to the web scrapper.

**Comment by Alexandru177** [comment]
What kind of data do you expect from it? For instance, this is how you'd call the API, with useful configurable options such as specifying engines or categories (useful for targeted research like academic or social media focused). Is this any different, broadly speaking, than what you receive with Tavily or Serper?
![Screenshot 2024-07-12 115948](https://github.com/user-attachments/assets/891b555d-7fc4-4ca1-a61e-a0f389664175)

**Comment by Alexandru177** [comment]
@miurla

**Comment by miurla** [comment]
PR: #309
