### ISSUE TITLE
[BUG] <Deployment on Vercel>

### ISSUE THREAD

**Issue by nathan0411** [miurla/morphic#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi! I am hosting a small website for my friends to use a custom version of the Morphic project where the research agent gives back witty responses alongside the needed information. I am trying to deploy it on Vercel, but when I get the results from the search, if the result is too long, the connection would just close. I suspect this to be because Vercel does not allow long API time calls, so I upgraded to the PRO version, but the behavior still persists. 

May I ask if you have encountered a similar behavior before while deploying? If not, what is your opinion on the root behind this issue. 

### Expected Behavior

The app should have worked similar to Morphic.sh, but with witty responses. 

### Steps To Reproduce

1. Deploy the project on Vercel 
2. Enter an inquiry
3. The inquiry starts generating, but upon almost completing, the connection would close, causing a crash 

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

### Anything else?

Thank you! I hope to hear some advice from you!

**Comment by miurla** [comment]
It is set in the `maxDuration` of each page.
With the Pro plan, it can be set up to a maximum of 5 minutes.

https://github.com/miurla/morphic/blob/main/app/page.tsx#L5

**Comment by nathan0411** [comment]
Thank you so much @miurla!
