### ISSUE TITLE
[BUG] ⨯ unhandledRejection: Error: .append(): The current value doesn't support appending data. Type: object

### ISSUE THREAD

**Issue by ifreeman6** [miurla/morphic#234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I meet this error when I try to run a query....

### Expected Behavior

....

### Steps To Reproduce

...

### Environment

```markdown
- OS:
- Browser:Edge browser
```

**Comment by miurla** [comment]
It seems that the issue might be related to the version of the libraries installed. Could you please confirm if you used the `bun install` command to install the dependencies?

**Comment by ifreeman6** [comment]
Thanks very much !  I have solved this issue when I use "bun install" to install it.

**Comment by rlawnahd** [comment]
bun을 사용하지 않고 node와 pnpm 을 사용중인데 위와 같은 에러가 계속 발생합니다,,
