### ISSUE TITLE
[BUG] Errror when sending follow-ups

### ISSUE THREAD

**Issue by alexey-kudryavtsev** [miurla/morphic#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using morphic.sh website as a search engine for browser omnibar. Custom search engine string that I use is `https://www.morphic.sh/search?q=%s`. When I send my query via this CSE, browser correctly renders an answer. But if I need to clarify and submit a follow-up question, I get an error:
<img src="https://github.com/miurla/morphic/assets/28059571/7080f73c-9ae1-4325-8666-cc4b02395341" width="300">

Note:
- if I navigate to morphic.sh normally and start a chat via main page input field, this behavior does not reproduce
- if I am logged out of morphic.sh, the behavior does not reproduce, all works fine
- if after getting the initial answer I manually refresh the page before submitting a follow-up question, there is also no error
- after getting this error I can find my chat in chat history and select it, there is nothing wrong with the chat, it loads and I can send follow-up questions normally without getting any errors.

### Expected Behavior

The error does not occur. There is no need to manually force-refresh page for follow-ups to work.

### Steps To Reproduce

1. Log into morphic.sh (I used google OAuth if that matters)
2. In browser's address field put https://www.morphic.sh/search?q=sometext and press enter
3. Wait for the morphic.sh page to render and the answer to fully load.
4. Scroll to the bottom of the page, find follow-up input field, write anything and submit
5. The error page is shown

### Environment

```markdown
- OS: Win11
- Browser: Edge 126.0.2592.61
```

**Comment by miurla** [comment]
@alexey-kudryavtsev 
Thanks to your detailed description of the bug, I was able to reproduce it easily. I've fixed it. 
If you have any feedback, please feel free to let me know.
