### ISSUE TITLE
Does it have to be the API key for gpt-4-turbo?

### ISSUE THREAD

**Issue by onlinedear** [miurla/morphic#25]
` AI_APICallError: The model `gpt-4-turbo` does not exist or you do not have access to it.
    at (node_modules/ai/openai/dist/index.mjs:265:0)
    at (node_modules/ai/openai/dist/index.mjs:176:0)
    at (node_modules/ai/openai/dist/index.mjs:609:0)
    at (node_modules/ai/dist/index.mjs:405:0)
    at (node_modules/ai/dist/index.mjs:1416:29)
    at (lib/agents/researcher.tsx:38:17)
    at (app/action.tsx:63:31) {
  name: 'AI_APICallError',
  url: 'https://api.openai.com/v1/chat/completions',
  requestBodyValues: {
  model: 'gpt-4-turbo',
  logit_bias: undefined,
  user: undefined,
  max_tokens: 2500,
  temperature: 0,
  top_p: undefined,
  frequency_penalty: 0,
  presence_penalty: 0,
  seed: undefined,
  messages: [
  {
  role: 'system',
  content: 'As a professional search expert, you possess the ability to search for any information on the web. \n    For each user query, utilize the search results to their fullest potential to provide additional information and assistance in your response.\n    If there are any images relevant to your answer, be sure to include them as well.\n    Aim to directly address the user\'s question, augmenting your response with insights gleaned from the search results.\n    Whenever quoting or referencing information from a specific URL, always cite the source URL explicitly.\n    '
},
  {
  role: 'user',
  content: [
  { type: 'text', text: '{"input":"Why is Nvidia growing rapidly?"}' }
]
}
],
  tools: [
  {
  type: 'function',
  function: {
  name: 'search',
  description: 'Search the web for information',
  parameters: {
  type: 'object',
  properties: {
  query: { type: 'string', description: 'The query to search for' },
  max_results: {
  type: 'number',
  maximum: 20,
  default: 5,
  description: 'The maximum number of results to return'
},
  search_depth: {
  type: 'string',
  enum: [ 'basic', 'advanced' ],
  default: 'basic',
  description: 'The depth of the search'
}
},
  required: [ 'query' ],
  additionalProperties: false,
  $schema: 'http://json-schema.org/draft-07/schema#'
}
}
}
],
  stream: true
},
  statusCode: 404,
  responseBody: '{\n    "error": {\n        "message": "The model `gpt-4-turbo` does not exist or you do not have access to it.",\n        "type": "invalid_request_error",\n        "param": null,\n        "code": "model_not_found"\n    }\n}\n',
  cause: undefined,
  isRetryable: false,
  data: {
  error: {
  message: 'The model `gpt-4-turbo` does not exist or you do not have access to it.',
  type: 'invalid_request_error',
  param: null,
  code: 'model_not_found'
}
}
}`

**Comment by winniesi** [comment]
you can set the model you need by setting the environment variable OPENAI_API_MODEL='gpt-4', if not set, the default is gpt-4-turbo.
