### ISSUE TITLE
Issue when opening Morphic website

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#252]
![Screenshot_20240707_060951_Chrome.jpg](https://github.com/miurla/morphic/assets/168287279/d12be7fb-5b99-46a3-9951-4506af8105e1)

This is happening when I try to open official Morphic website. It doesn't usually do this. Please fix this 🙂

**Comment by miurla** [comment]
The error has been resolved. Thank you for reporting the error.
