### ISSUE TITLE
Quality (claude) inaccuracy in response

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#260]
![Screenshot_20240715_213958_Chrome.jpg](https://github.com/user-attachments/assets/fc75c26f-a630-4ebc-8bce-98f2acb72da8)

You can see in the screenshot that it said, in the first quarter of fiscal (2025), Nvidia beat expectations, etc. And then again, in second paragraph, it said in Q1 FY(2025), the company exceeded revenue growth expectations. 

It should say in 2024 as it's not 2025 yet. So accuracy of Quality (Claude) has to be improved further.

**Comment by miurla** [comment]
@ZainGithub12 Thank you for the report. Could you provide the share link for this page?

**Comment by ZainGithub12** [comment]
@miurla Of course, here it is, https://www.morphic.sh/share/kS1qZK1

**Comment by miurla** [comment]
Thank you for sharing. Did you check the source link? https://www.nasdaq.com/articles/why-nvidia-rocketed-nearly-150-first-half-2024
This is according to Nvidia's fiscal year and is not a mistake. Please ask follow-up questions to confirm the details.

**Comment by ZainGithub12** [comment]
@miurla Okay, i checked the source link as well now and seen it. 👍
