### ISSUE TITLE
Error happening with only (Quality) Claude..

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#261]
![Screenshot_20240716_124550_Chrome.jpg](https://github.com/user-attachments/assets/d45e7820-afff-43d8-8010-ef6fefd5baa2)

@miurla, I tried with other models and they're fine, it's just with the Claude model.
Sometimes it happens, sometimes not.

**Comment by ZainGithub12** [comment]
@miurla, this is today
![Screenshot_20240717_091910_Chrome.jpg](https://github.com/user-attachments/assets/08989130-ed29-460e-99f7-4b800877485d)

**Comment by miurla** [comment]
As indicated by the error, there were frequent Claude API errors. I contacted Anthropic support, and the issue has now been resolved.

**Comment by ZainGithub12** [comment]
@miurla, this is today
![Screenshot_20240717_091910_Chrome.jpg](https://github.com/user-attachments/assets/08989130-ed29-460e-99f7-4b800877485d)

Thank you

**Comment by ZainGithub12** [comment]
@miurla 👍
