### ISSUE TITLE
Future feature possibilities 

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#267]
@miurla, As a regular user of Morphic, i'm just wondering if there are future plans to incorporate vision, audio, video, and file upload capabilities.

**Comment by miurla** [comment]
Hey @ZainGithub12, thank you for always providing feedback.

We're considering enabling image and file uploads. Additionally, we plan to add voice recognition to the query prompt. This is just a plan for now.

**Comment by ZainGithub12** [comment]
@miurla Okay, sounds good! I think it would also be cool to add OpenAI's future Sora text-to-video model, too. Or something similar in future, unless OpenAI or Microsoft release the model for free. And also voice-to-voice interaction with Morphic. But if that's not possible, then I'm okay with that. 🙂
