### ISSUE TITLE
Swap llama-3-70b Groq with llama-3.1-405b Groq model

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#274]
Can you swap the Llama-3-70b Groq model with Llama-3.1-405b Groq model?

**Comment by miurla** [comment]
Updated the lightning mode model from llama-3-70b to llama-3.1-70b. We can't access 405b model yet.

> Early API access to Llama 3.1 405B is currently available to select Groq customers only – stay tuned for general availability. We will also be sharing independent 3rd party benchmarks demonstrating Groq speed across Llama 3.1 models very soon. 

https://wow.groq.com/now-available-on-groq-the-largest-and-most-capable-openly-available-foundation-model-to-date-llama-3-1-405b/

ref: #275

**Comment by ZainGithub12** [comment]
@miura, Okay 👍
