### ISSUE TITLE
 Errors happening with Llama-3.1-70b mode

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#277]
![Screenshot_20240724_163455_Chrome.jpg](https://github.com/user-attachments/assets/f407f3cc-ec7d-4970-8b7b-3f33d034cf99)

@miurla, This happens when I do this prompt:

![Screenshot_20240724_164006_Chrome.jpg](https://github.com/user-attachments/assets/2d095e4b-2210-41d7-ad61-9caa69bf938e)

**Comment by miurla** [comment]
We’re currently inquiring with the Groq team.

**Comment by ZainGithub12** [comment]
@miurla, 👍

**Comment by ZainGithub12** [comment]
@miurla Are you still inquiring with the team? Because lightning mode also disappeared from Morphic. Is this because it's being fixed?

**Comment by miurla** [comment]
Yes, we dropped it until the error is resolved.

**Comment by ZainGithub12** [comment]
@miurla ok 👍
