### ISSUE TITLE
[BUG] groq cannot be used

### ISSUE THREAD

**Issue by calathus** [miurla/morphic#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

even if we provided  groq related info in .env.local file in SPECIFIC_API_BASE, etc, it does not use this info and use open api(since I intend to only groq). 

### Expected Behavior

just it should use groq if we provide such info in .env.local file.

### Steps To Reproduce

1)
USE_SPECIFIC_API_FOR_WRITER=true
SPECIFIC_API_BASE=https://api.groq.com/openai/v1
SPECIFIC_API_KEY=gsk_XXXXXXXXXXXXXX
SPECIFIC_API_MODEL=llama3-groq-70b-8192-tool-use-preview
2)
bun dev
3) in browser, type/search:
report the research of projective invariant feature extraction of image using geometric algebra.

### Environment

```markdown
- OS:Ubuntu 22
- Browser:Firefox
```

### Anything else?

I already fixed the issue, so I will make pull request.

I noticed, morphic use function call, so modele like llama-3.1-70b-versatile which does not support it will fail. So right now there only two such models in groq(8/1/2024). llama3-groq-70b-8192-tool-use-preview, llama3-groq-8b-8192-tool-use-preview.
-- but if we don't need such feature, it seems better to use  normal models. so there should be such internal optimization to switch model depend on the usecase.

**Comment by johngoad** [comment]
Hey, just looking over that set up. Are you paying for groq? I know the preview models are not for free. I will try and reproduce anyway... I learned this when they first came out, and I kept trying to add models from this page... https://console.groq.com/docs/models using the bold titles of the models... After about a half a day, I learned that you have to enter it in exactly as it is right after the "Model ID:" line that includes the context window.



**Meta Llama 3 70B**

Model ID: llama3-70b-8192
Developer: Meta
Context Window: 8,192 tokens

**Comment by miurla** [comment]
This is not a bug. If you only use Groq's model with Morphic, you need to support Groq Provider. Details are commented on the PR: https://github.com/miurla/morphic/pull/288#issuecomment-2266323861

We will support Groq Provider when we are able to. #289
