### ISSUE TITLE
[BUG] Error: fetch() URL is invalid -- When clicked on default "What is GPT-4o mini?" link

### ISSUE THREAD

**Issue by piovis2023** [miurla/morphic#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

C:\Documents\07. AI\morphic\.next\server\chunks\ssr\

When clicked on default "What is GPT-4o mini?" link on the opening screen, this error occurred  Error: fetch() URL is invalid.

API response:
$ next dev --turbo
  ▲ Next.js 14.2.5 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1346ms
 ○ Compiling / ...
 ✓ Compiled / in 5.3s
 GET / 200 in 6385ms
 GET / 200 in 430ms
 GET / 200 in 399ms
 GET / 200 in 401ms
 GET / 200 in 1684ms
 ○ Compiling /search/[id] ...
 ✓ Compiled /search/[id] in 1341ms
11470 |                         ...init == null ? void 0 : init.next,
11471 |                         fetchType: "origin",
11472 |                         fetchIdx
11473 |                     }
11474 |                 };
11475 |                 return originFetch(input, clonedInit).then(async (res)=>{
                               ^
TypeError: fetch() URL is invalid
 code: "ERR_INVALID_ARG_VALUE"

      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11475:24
      at doOriginalFetch (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11429:53)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11626:24
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11283:22
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:10639:36
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11269:20
      at patched (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11251:35)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2433:32      
      at postToApi (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2430:26)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2416:126     
      at postJsonToApi (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2416:35)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:4811:54      
      at doGenerate (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:4808:22)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:667:28
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:95:22
      at _retryWithExponentialBackoff (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:93:50)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:88:148
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:88:116
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:666:46
      at generateObject (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:640:33)  
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:1076:34
      at taskManager (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:1074:28)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2254:39
      at processEvents (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2241:36)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2417:5
      at $$ACTION_0 (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2195:27)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_68d4f9._.js:5065:194

 POST /search/ZxqMNb0 200 in 2226ms
The streamable value has been slow to update. This may be a bug or a performance issue or you forgot to call `.done()`.
11470 |                         ...init == null ? void 0 : init.next,
11471 |                         fetchType: "origin",
11472 |                         fetchIdx
11473 |                     }
11474 |                 };
11475 |                 return originFetch(input, clonedInit).then(async (res)=>{
                               ^
TypeError: fetch() URL is invalid
 code: "ERR_INVALID_ARG_VALUE"

      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11475:24
      at doOriginalFetch (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11429:53)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11626:24
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11283:22
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:10639:36
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11269:20
      at patched (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_next_eac60f._.js:11251:35)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2433:32      
      at postToApi (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2430:26)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2416:126     
      at postJsonToApi (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:2416:35)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:4811:54      
      at doGenerate (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\node_modules_9f757d._.js:4808:22)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:667:28
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:95:22
      at _retryWithExponentialBackoff (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:93:50)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:88:148
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:88:116
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:666:46
      at generateObject (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_9c4c19._.js:640:33)  
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:1076:34
      at taskManager (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:1074:28)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2254:39
      at processEvents (C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2241:36)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2417:5
      at $$ACTION_0 C:\Documents\07. AI\morphic\.next\server\chunks\ssr\[root of the server]__5076e3._.js:2195:27)
      at C:\Documents\07. AI\morphic\.next\server\chunks\ssr\_68d4f9._.js:5065:194

 POST /search/ZxqMNb0 200 in 286ms
The streamable value has been slow to update. This may be a bug or a performance issue or you forgot to call `.done()`

### Expected Behavior

Retrieve info from URLs

### Steps To Reproduce

Install on Windows 11 OS
Run on Brave broswer
Click one of the links on the opening page or type in a query

env file keys entered
Open AI = No
Tavily = Yes
Gemini = Yes
Ollama = Yes (OLLAMA_MODEL=mistral-nemo:12b-instruct-2407-q5_0 and OLLAMA_SUB_MODEL=llama3.1:8b-instruct-q8_0)
Upstash = Yes

### Environment

```markdown
- OS: Windows 11
- Browser: Brave
```

### Anything else?

If I make the following changes in the .env file by doing the following and re-run, I get a new error "Error: Failed to process successful response":
1. commenting out OpenAi lines
2. Correct line 40  from Llama _Base_URL to Ollama_Base_URL

API response error:
$ next dev --turbo
  ▲ Next.js 14.2.5 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1346ms
 ○ Compiling / ...
 ✓ Compiled / in 5.3s
 GET / 200 in 6385ms
 GET / 200 in 430ms
 GET / 200 in 399ms
 GET / 200 in 401ms
 GET / 200 in 1684ms
 ○ Compiling /search/[id] ...
 ✓ Compiled /search/[id] in 1341ms
11470 |                         ...init == null ? void 0 : init.next,
11471 |                         fetchType: "origin",
11472 |                         fetchIdx
11473 |                     }
11474 |                 };
11475 |                 return originFetch(input, clonedInit).then(async (res)=>{

**Comment by miurla** [comment]
The Ollama provider is unstable. Please check this issue: https://github.com/miurla/morphic/issues/215#issue-2342253705
