### ISSUE TITLE
Repeated trending topic

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#298]
![Screenshot_20240810_140612_Chrome.jpg](https://github.com/user-attachments/assets/4278b21a-1f18-4825-b203-830a845f2845)

@miurla, As you can see, the trending topics mentioned google photos library replacement with collections twice. Another example below:

![Screenshot_20240810_141813_Chrome.jpg](https://github.com/user-attachments/assets/30f623a5-792a-4282-bae0-e325fc12545f)

**Comment by miurla** [comment]
fixed
