### ISSUE TITLE
Wait, can I bring back the cute looking character w/ eyes that follow my mouse in my prod?

### ISSUE THREAD

**Issue by solomonshalom** [miurla/morphic#321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It doesn't have the character

### Expected Behavior

Would love to see the character!

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: Windows
- Browser: Edge
```

**Comment by miurla** [comment]
Please read this note: https://github.com/miurla/morphic?tab=readme-ov-file#morphic
