### ISSUE TITLE
I'm trying to upload image, and ask what Morphic sees. (Chat loading failed) pops up after sending message. (Free plan speed mode)

### ISSUE THREAD

**Issue by ZainGithub12** [miurla/morphic#326]
![Screenshot_20240901_224211_Chrome.jpg](https://github.com/user-attachments/assets/7763f531-cc25-4c73-a8d5-0c28c3835fc3)

@miurla how many images can we upload on free plan?

**Comment by miurla** [comment]
When you upload an image, does a loading error always occur? As far as we are monitoring the error logs, no issues have occurred where errors only happen during image uploads.

**Comment by ZainGithub12** [comment]
For some reason, it happens with one image but others are fine actually.
