### ISSUE TITLE
[BUG] Why is morphic.sh different to the open source version in terms of UI?

### ISSUE THREAD

**Issue by mrisaacjoy** [miurla/morphic#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Vercel Runtime Logs

- [ ] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

Go to morphic.sh, it looks different

### Expected Behavior

If Morphic.sh is open source, why aren't they the same UI?

### Steps To Reproduce

Go to morphic.sh, look 
Run morphic locally + look

### Environment

```markdown
- OS: Mac
- Browser: Chrome
```

**Comment by miurla** [comment]
Please read this note: https://github.com/miurla/morphic?tab=readme-ov-file#morphic
