### ISSUE TITLE
Something other than Tavily

### ISSUE THREAD

**Issue by dillfrescott** [miurla/morphic#34]
Tavily gives you only 1,000 requests a month, and after that the base plan is a staggering $100 a month.

Perhaps using searxng would be a better option.

**Comment by miurla** [comment]
Tavily and Exa are embeddings-based search APIs designed for use by LLMs. Can you achieve the same results with SearXNG?

Also, do you need more than 1000 queries per month for personal use?

**Comment by peperunas** [comment]
Another point in favor of SearxNG is the local deployment of the search engine - and, subsequently, the possibility to use different instances.

**Comment by miurla** [comment]
Transfer to a feature request issue: https://github.com/miurla/morphic/issues/196
