### ISSUE TITLE
[Feature]  Add a login or password please

### ISSUE THREAD

**Issue by mwnu** [miurla/morphic#35]
I want to access it outside the LAN and share it with my family, but GPT-4 is expensive. I tested GPT-3.5 and the Claude-3 model proxy compatible with the OpenAI API, but couldn't effectively implement the agent.
So...

**Comment by MorningInsight3** [comment]
[same issue](https://github.com/miurla/morphic/issues/32)
https://github.com/miurla/morphic/issues/32

**Comment by mwnu** [comment]
> [same issue](https://github.com/miurla/morphic/issues/32) #32

Not the same

**Comment by bean4896** [comment]
a login entrance will make this app very powerful

**Comment by miurla** [comment]
We don't plan to add authentication.
reason: https://github.com/miurla/morphic?tab=readme-ov-file#morphic
