### ISSUE TITLE
[BUG] Gemini Model fails to invoke any tools.

### ISSUE THREAD

**Issue by essamamdani** [miurla/morphic#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Vercel Runtime Logs

- [ ] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

I switched from OpenAI to Google Gemini Flash 1.5. It now directly provides answers using the LLM. However, after two hours, I noticed the 'toolChoice: required' setting in the Vercel AI SDK. As a result, the output continuously triggered search cards without stopping the process or generating responses based on the search results.

Here is some snaps:
<img width="732" alt="Screenshot 2024-10-01 at 4 58 00 AM" src="https://github.com/user-attachments/assets/ef453e58-5973-441e-9baf-1cb6eadee9c0">
<img width="379" alt="Screenshot 2024-10-01 at 4 59 53 AM" src="https://github.com/user-attachments/assets/355f26c1-87ba-4f0d-a12a-9090d1e0ab89">
<img width="397" alt="Screenshot 2024-10-01 at 4 59 45 AM" src="https://github.com/user-attachments/assets/111ea044-04fb-489f-9eac-c6ecb01e2f3e">

### Expected Behavior

It should function the same way as OpenAI’s GPT-4 version.

### Steps To Reproduce

1. I just added the Generative API key to the `.env` file.  
2. After that, I received answers directly from the LLM without any tools being executed.  
3. Later, I found the `toolChoice: 'required'` option and added it to the `researcher.tsx` file.

### Environment

```markdown
- OS:Mac
- Browser:Chrome
```

### Anything else?

"@ai-sdk/google": "0.0.23",
"@google/generative-ai": "^0.3.1",
 "ai": "^3.2.10",

**Comment by miurla** [comment]
This error is an issue with the Gemini model. If `toolChoice` is set to `auto` (default), the model decides whether to call the tool. If `toolChoice` is set to `required`, the model will call the tool as needed. This also depends on the model.

In the latest code, `maxSteps` is set to 5, so the tool should not continue to be called: https://github.com/miurla/morphic/blob/main/lib/agents/researcher.tsx#L30
https://sdk.vercel.ai/docs/ai-sdk-core/tools-and-tool-calling#multi-step-calls

Please try with the latest code.
https://github.com/miurla/morphic/blob/main/package.json#L15

**Comment by essamamdani** [comment]
it's still the same error. After I updated the packages
<img width="399" alt="Screenshot 2024-10-01 at 9 31 29 PM" src="https://github.com/user-attachments/assets/07afc096-8b57-4f12-85d0-3e541115da28">
<img width="552" alt="Screenshot 2024-10-01 at 9 32 29 PM" src="https://github.com/user-attachments/assets/b3602eca-b4f4-4d63-8576-057e8ef34b6c">

Still Don't call any tools: 
<img width="736" alt="Screenshot 2024-10-01 at 9 35 03 PM" src="https://github.com/user-attachments/assets/2af62322-298a-45d0-a822-9489476729ad">

**Comment by miurla** [comment]
> it's still the same error. After I updated the packages

No, I explained that in the latest version, the issue of continuously calling tools has been resolved.

**Comment by miurla** [comment]
I found that there are limitations in the schema of the Google Generative API: https://sdk.vercel.ai/providers/ai-sdk-providers/google-generative-ai#troubleshooting-schema-limitations

PR: #358 

It started calling tools. The model I confirmed was `gemini-1.5-pro-002`. `gemini-1.5-flash-002` did not call tools. This should be dependent on the model.

![image](https://github.com/user-attachments/assets/4c15ce63-bae8-4e64-9a7d-c23812675558)

**Comment by essamamdani** [comment]
Thanks Let me check.

**Comment by essamamdani** [comment]
Followed these steps:

`git clone https://github.com/miurla/morphic`
`cd morphic`
`bun install`
`nano .env` added GOOGLE_GENERATIVE_AI_API_KEY and other necessary environment variables
`bun run dev`

<img width="815" alt="Screenshot 2024-10-04 at 4 45 55 PM" src="https://github.com/user-attachments/assets/9135c4dc-fd63-42d6-a609-d38ccb3de3d1">

**Comment by miurla** [comment]
Did you tried some query?  **The model decides whether to call the tool**

![image](https://github.com/user-attachments/assets/0efa18be-07f4-4f47-966b-9d31bb053016)

**Comment by essamamdani** [comment]
How can we make forceable to call tool everytime before generating the answer?
