### ISSUE TITLE
[BUG] Enter Key Triggers Form Submission After Japanese Input on macOS Safari

### ISSUE THREAD

**Issue by snowyday** [miurla/morphic#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Vercel Runtime Logs

- [ ] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

On macOS using Safari, when inputting Japanese characters, pressing the Enter key immediately after confirming the input (i.e., when `compositionend` is fired) unexpectedly triggers form submission. This happens even though the user might not have intended to submit the form. This issue occurs because the `Enter` key event is processed too soon after Japanese Input Method input is confirmed.

### Expected Behavior

The form should only be submitted when the user explicitly presses Enter to submit after confirming Japanese input. Pressing Enter to confirm Japanese input should not trigger form submission immediately.

### Steps To Reproduce

Input Japanese.

### Environment

```markdown
- OS:　macOS 15.0.1
- Browser: Safari
```

### Anything else?

**Proposed Fix:**
To prevent immediate submission after Japanese input, I added a small delay after `compositionend` before enabling the Enter key to trigger form submission. This ensures the Japanese input process fully completes before allowing form submission.

**Minimal Reproducible Example:**

```tsx
import { useEffect, useState, useRef } from 'react'

function ChatPanel() {
  const [input, setInput] = useState('')
  const [isComposing, setIsComposing] = useState(false) // Japanese Input Method state
  const [enterDisabled, setEnterDisabled] = useState(false) // Disable Enter after Japanese Input Method composition ends

  useEffect(() => {
    const handleCompositionStart = () => setIsComposing(true)
    const handleCompositionEnd = () => {
      setIsComposing(false)
      // Disable Enter key for a short delay after Japanese Input Method composition ends
      setEnterDisabled(true)
      setTimeout(() => {
        setEnterDisabled(false)
      }, 300) // 300ms delay to ensure Japanese Input Method input confirmation
    }

    document.addEventListener('compositionstart', handleCompositionStart)
    document.addEventListener('compositionend', handleCompositionEnd)

    return () => {
      document.removeEventListener('compositionstart', handleCompositionStart)
      document.removeEventListener('compositionend', handleCompositionEnd)
    }
  }, [])

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey && !isComposing && !enterDisabled) {
      // Prevent default behavior (adding new line) and handle form submission logic here
      e.preventDefault()
      // Form submission logic (e.g., calling an API)
      console.log('Form submitted:', input)
    }
  }

  return (
    <textarea
      value={input}
      onChange={e => setInput(e.target.value)}
      onKeyDown={handleKeyDown}
      placeholder="Type your message..."
    />
  )
}

export default ChatPanel
```

**Proposed Solution:**
By introducing a small delay after `compositionend`, the Enter key is temporarily disabled, preventing unwanted form submissions immediately after Japanese Input Method input confirmation. This solution has resolved the issue in my testing.

[fixed version: chat-panel.tsx](https://gist.github.com/snowyday/76ff3c0138bcf83a2ee8ffe97ce7150d#file-chat-panel-tsx)

Please review this fix, and consider integrating it to prevent this bug in macOS Safari environments.

**Comment by miurla** [comment]
@snowyday Thank you for reporting the bug report. I was able to confirm the reproduction.

The approach for your solution is good. Instead of using a global event listener, you can add an event listener directly to the textarea element.

```typescript
<Textarea 
...
onCompositionStart={handleCompositionStart}
onCompositionEnd={handleCompositionEnd}
...
/>
```

Could you create a PR for this?

**Comment by snowyday** [comment]
@miurla I've reviewed the changes, and everything looks good.
You can check the updated version here: [fixed version: chat-panel.tsx](https://gist.github.com/snowyday/76ff3c0138bcf83a2ee8ffe97ce7150d).
I'll proceed with creating the PR!

**Comment by miurla** [comment]
@snowyday Thank you, looks good 👍
