### ISSUE TITLE
[BUG] Bun Build and Bun start not supported?

### ISSUE THREAD

**Issue by ncecere** [miurla/morphic#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Vercel Runtime Logs

- [x] I have checked the Vercel Runtime Logs for errors (if applicable)

### Current Behavior

I'm trying to make a version of the dockerfile and docker compose where I build the application and then start it with bun start.  but the container never builds.

### Expected Behavior

Application build and I can use Bun start to run

### Steps To Reproduce

1. Bun build

### Environment

```markdown
- OS: osx
- Browser: Firefox
```

**Comment by ncecere** [comment]
I'm more wondering If I'm missing something or if this isn't supported

**Comment by Sathwik-Amburi** [comment]
> I'm more wondering If I'm missing something or if this isn't supported

Did you try `bun run build` ? 

`bun build ` is a built-in command for optimizing and bundling files in Bun projects, while `bun run build` runs the custom "build" script defined in the project's package.json (which is to build the nextjs project).

**Comment by miurla** [comment]
This issue can be resolved by using the correct commands:

1. Use `bun run build` instead of `bun build` for Next.js projects
2. Then use `bun start` to run the built application
