### ISSUE TITLE
Author, I followed your steps to install and encountered this error after running. How can I improve it?

### ISSUE THREAD

**Issue by yxl23** [miurla/morphic#46]
![image](https://github.com/miurla/morphic/assets/115678682/14041ee0-d72e-41a2-a410-5e31de2528c0)

**Comment by StevenOng97** [comment]
rename postcss.config.mjs => postcss.config.cjs

in the file:
change export default config => module.exports = config;

**Comment by yxl23** [comment]
Thanks to the author, my problem solved

**Comment by miurla** [comment]
It can be resolved without any changes.
Please try with the latest code & `bun install`

https://github.com/miurla/morphic/issues/16#issuecomment-2058410971
