### ISSUE TITLE
Inquiry About Commercial Licensing for Deployed Version

### ISSUE THREAD

**Issue by aaronpeng2020** [miurla/morphic#48]
Hello,

I've noticed that the repository on GitHub seems to differ from the version deployed at https://www.morphic.sh/. Are there any plans to offer a commercial licensing plan? I would be very interested in purchasing a commercial license to use the deployed version.

Thank you for your attention to this matter.

**Comment by miurla** [comment]
Hi @aaronpeng2020 

Thank you for your inquiry. It's a very interesting proposal. I had never considered licensing. 
However, I'm focused on the development of the main project, so I won't be able to accommodate that. 
Currently, there are many authentication products available, and it's easier to integrate them than before. 
Please give it a try.

**Comment by aaronpeng2020** [comment]
> Hi @aaronpeng2020
> 
> Thank you for your inquiry. It's a very interesting proposal. I had never considered licensing. However, I'm focused on the development of the main project, so I won't be able to accommodate that. Currently, there are many authentication products available, and it's easier to integrate them than before. Please give it a try.

No, what I meant is that I would like to use the project you developed for commercial purposes, and I would like to obtain your paid license.
I don't need you to do anything extra; I just hope that the features of the commercial version can be the same as those on https://www.morphic.sh/.

Every developer needs to make a living, and I hope there is a way to financially support your continued development.

**Comment by junaid33** [comment]
I think it should be clear that the hosted version (morphic.sh) is not the same version open-sourced here.

**Comment by miurla** [comment]
We don't plan to add authentication.
reason: https://github.com/miurla/morphic?tab=readme-ov-file#morphic
