### ISSUE TITLE
用vercel部署后是这样的

### ISSUE THREAD

**Issue by moinkhaop** [miurla/morphic#49]
感觉只用上了gpt(用的是月之暗面的kimi)生成文本，没有用上那个搜索，但环境变量里都添加了，求解！！！
![image](https://github.com/miurla/morphic/assets/122024362/6a0100bf-97ec-4bc0-90db-d4fc49fbc484)

**Comment by superlbr** [comment]
whether use function call or not, is decided by gpt

**Comment by superlbr** [comment]
there is a parameter `toolChoice`
![image](https://github.com/miurla/morphic/assets/8142164/0a670a1a-72af-4230-a477-d4b09054fffc)
