### ISSUE TITLE
Enable specifying anthropic as the provider for the Writer agent

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#60]
https://github.com/miurla/morphic/blob/main/lib/agents/writer.tsx#L27
https://sdk.vercel.ai/docs/ai-core/anthropic

**Comment by Nil2000** [comment]
Hi @miurla Can you assign me this task?

**Comment by miurla** [comment]
Thank you!

**Comment by miurla** [comment]
Thank you for your contribution ✨
