### ISSUE TITLE
Include videos in the search results

### ISSUE THREAD

**Issue by miurla** [miurla/morphic#61]
> serper api could be used to fetch the videos

SerperAPI: https://serper.dev/

**Comment by albertdbio** [comment]
Hey @miurla is something I've been thinking about implementing.
Wanted to get your opinion before I proceed.
Would you prefer to add a custom markdown component that parses youtube urls and embeds them or would you want to stream a video component from the server?

**Comment by miurla** [comment]
@albertdbio 

Awesome! How cool are you. 

Just like the image section, I want to add a video section and create a component that embeds YouTube. I think it'd be best if, when clicking on a video thumbnail, it enlarges in a modal just like images and plays.

In addition to the search tool, I'm thinking of adding a video search tool and envisioning it to be called by tool calling when the agent needs it, but do I have the right understanding with you?

https://github.com/miurla/morphic/blob/main/lib/agents/researcher.tsx#L50

If anything is unclear, please feel free to ask more questions.

**Comment by miurla** [comment]
I'm working on this feature.
