### ISSUE TITLE
Make the search box a textarea.

### ISSUE THREAD

**Issue by skyler14** [miurla/morphic#66]
This change would be relatively minor but fall in line with Google which ditched the input field for a text area a long time ago. It allows for longer inputs, multi-line, doesn't suppress certain characters and formatting, and makes typing a more detailed searrch easier on a phone keyboard. There are actually alot of other compelling reasons why they switched to a textarea, for example better accessibility option handling and being able build better interfaces on top of it.

**Comment by Techno-o76** [comment]
I am new to open source, how can i pick up this issue. Willing to resolve this issue.

**Comment by miurla** [comment]
@Techno-o76 

I appreciate your willingness to work on resolving this issue. You can use the following library for automatically resizing TextArea elements:
https://github.com/Andarist/react-textarea-autosize

Please refer to it for your implementation.

**Comment by Techno-o76** [comment]
ThankYou @miurla, I have referred that repo and currently i'm working on it.

**Comment by Techno-o76** [comment]
@miurla I have tried to add the TextareaAutosize component but its not props are not compatible and throwing multiple errors.
![Screenshot 2024-04-26 000958](https://github.com/miurla/morphic/assets/91217271/634026a4-dfb8-4c82-93a9-070df5c51d8d)

I have tried https://mui.com/base-ui/react-textarea-autosize/components-api/  and it's working perfectly fine without any errors.
![image](https://github.com/miurla/morphic/assets/91217271/463d6a26-07cf-4414-aac2-1062d29fde99)

Please review it.

**Comment by miurla** [comment]
@Techno-o76 
Thank you for trying.
ReactTextAreaAutosize has already become a utility component, so there is no need to create a wrapped component.
You can look at the implementation of the Vercel Chatbot.

https://github.com/vercel/ai-chatbot/blob/main/components/prompt-form.tsx#L86-L100

**Comment by miurla** [comment]
@Techno-o76 
There was a PR from another contributor. I apologize for the inconvenience as you were working on it.
I hope you can contribute to another issue.

https://github.com/miurla/morphic/pull/86

**Comment by skyler14** [comment]
Btw, only the first text box is a textarea currently. All the same problems still pop up when you continue querying on a thread, so this needs to be copy pasted over that component


> @Techno-o76 There was a PR from another contributor. I apologize for the inconvenience as you were working on it. I hope you can contribute to another issue.
> 
> #86
