### ISSUE TITLE
should it export edge runtime from client component?

### ISSUE THREAD

**Issue by luismartinezs** [miurla/morphic#68]
Does it make sense to use edge runtime in a client component? I'm genuinely curious as it doesn't seem to make intuitive sense but I cannot find any explicity mention of it in the nextjs docs

```
// app/page.tsx
'use client'

export const runtime = 'edge'
```

**Comment by miurla** [comment]
It's a workaround to address a streaming issue that only occurs on Vercel.
I've commented on the issue, but I'm not sure if this is the correct solution.

https://github.com/vercel/ai/issues/1187#issuecomment-2064115795

**Comment by miurla** [comment]
Ahh... I think you should remove the `use client`. I forgot to remove it after creating the Chat component.

**Comment by miurla** [comment]
Removed. Thank you for pointing that out.
