### ISSUE TITLE
Will there be support for history conversations?

### ISSUE THREAD

**Issue by yinan-c** [miurla/morphic#7]
Thanks for the project, it would be perfect if there is a side panel with all the conversation histories.

**Comment by saurabhgaur** [comment]
Vercel demo project makes use of   unstable_onSetAIState to persist Chat messages and unstable_onGetUIState with getUIStateFromAIState to map back the saved messages to UI components. I will be great to see something like that here.

**Comment by miurla** [comment]
I can implement that. However, even using Vercel's KV for persistence, it won't be as simple to deploy as it is now. That's my only concern.
What do you all think?

https://github.com/vercel/ai-chatbot?tab=readme-ov-file#creating-a-kv-database-instance

**Comment by aaronpeng2020** [comment]
> I can implement that. However, even using Vercel's KV for persistence, it won't be as simple to deploy as it is now. That's my only concern. Probably even those who are not developers are deploying and using it on Vercel.我可以实现这个功能。然而，即使使用 Vercel 的 KV 进行持久化，部署起来也不会像现在这么简单。这是我唯一的担忧。甚至那些不是开发人员的人也在 Vercel 上部署和使用它。
> 
> https://github.com/vercel/ai-chatbot?tab=readme-ov-file#creating-a-kv-database-instance


This feature is very important, and I hope you will consider it.
It could be an optional setting that is not enabled by default for those who are not familiar with how to deploy it.

**Comment by miurla** [comment]
OK. It's planned to be addressed as the next feature.

**Comment by saurabhgaur** [comment]
Thanks a lot. Looking forward to it!
