### ISSUE TITLE
Issue deploying to Vercel possibly related to Next.js version (405 error)

### ISSUE THREAD

**Issue by albertdbio** [miurla/morphic#85]
# Reproduction

1. Clone the repo
2. Run `vercel`
3. Visit the url where it was deployed
4. Perform a search

# Research

Previous deployments worked just fine. Even when deploying from the official Vercel [template](https://vercel.com/templates/next.js/morphic-ai-answer-engine-generative-ui) it will still give you the 405 error.

I've attached the screenshot and a url to a fresh deployment for verification.

https://morphic-fourofive-error.vercel.app/

<img width="1056" alt="Screenshot 2024-04-25 at 7 04 55 PM" src="https://github.com/miurla/morphic/assets/94892833/c77e1954-b52a-4a01-a9ff-64b3458372d1">

# Possible solution

@miurla can you verify which version of Next is working.
May we also update the bun lock file to use more specific versions instead of `latest`

Thanks for you work @miurla!
Hope this prevents further deployment issues.

**Comment by miurla** [comment]
Thank you for the report. I have confirmed the error.
I suspected the recent commits, but they were not the cause.

There is no problem with the Deployment Link in Vercel's preview, but an error occurs with the Branch Link. It depends on Vercel's environment. I don't think it's related to the version of nextjs.

It might take some time to resolve the error.

**Comment by albertdbio** [comment]
Oh wow very strange.
I can help you debug.
I'll report any findings here.

**Comment by albertdbio** [comment]
I'm going to try to use a previous ai sdk version.

**Comment by albertdbio** [comment]
Found a fix, it might actually be the next.js version

**Comment by albertdbio** [comment]
Yup it was a next version.
See pr: https://github.com/miurla/morphic/pull/90

**Comment by miurla** [comment]
@albertdbio 

Thank you for solving it! 
My guess was wrong. It was very helpful. I appreciate your contribution.

**Comment by miurla** [comment]
> There is no problem with the Deployment Link in Vercel's preview, but an error occurs with the Branch Link. It depends on Vercel's environment.

It seems the issue was caused by the main branch becoming inoperative. After merging, it's working. We'll be careful when upgrading to the next.js version.

**Comment by albertdbio** [comment]
Glad to help out 🙏

**Comment by aleksa-codes** [comment]
As I'm following the PR #5, I noticed this issue and would like to mention that it could be connected to the ongoing discussion, as I encountered a similar issue in my project as well: [link to discussion](https://github.com/orgs/vercel/discussions/6651#discussion-6563996).

I guess the solution for now is to either downgrade the  Next.js version or the Vercel CLI version.

**Comment by miurla** [comment]
@aleksa-codes  Thanks for sharing. It's the same issue.
PR #5 is running on node instead of edge runtime, but the same problem is occurring.
