### ISSUE TITLE
fix: typo in chat panel component

### ISSUE THREAD

**Issue by srizvi** [miurla/morphic#88]
Hey @miurla, hat's off to you and thank you for your incredible contributions. I noticed this and believe it should be updated to `fixed bottom-8 -ml-6` at your convenience.

https://github.com/miurla/morphic/blob/59139820e5031e6030ba0cd32463e144ab3a6601/components/chat-panel.tsx#L88C10-L88C29

**Comment by miurla** [comment]
Thank you for pointing that out. I've removed it since it was unnecessary code.
