### ISSUE TITLE
TypeError after vercel deployment.

### ISSUE THREAD

**Issue by ibelieve3212** [miurla/morphic#95]
![image](https://github.com/miurla/morphic/assets/70727665/eed02660-4f3c-4c6e-957a-749562000812)
![image](https://github.com/miurla/morphic/assets/70727665/572087ba-f0af-48d6-881d-eba12240fd12)
![image](https://github.com/miurla/morphic/assets/70727665/0ea14296-ef1f-4970-96af-4daf96a9b25b)

Here's the error message:
TypeError: Right-hand side of 'instanceof' is not an object
    at (node_modules/ai/node_modules/@ai-sdk/provider-utils/dist/index.mjs:33:0)
    at (node_modules/ai/dist/index.mjs:302:20)

The home page displays fine, but after searching for content it keeps getting stuck on loading, do I need to add any more variables?

**Comment by miurla** [comment]
`OPENAI_API_KEY` and `TAVILY_API_KEY` aren't optional values. If they are not set, an error will occur.
https://github.com/miurla/morphic?tab=readme-ov-file#3-fill-out-secrets

`OPENAI_API_KEY` is not set. Also, the value of `TAVILY_API_KEY` does not contain the key value.

Also, when using SPECIFIC_API, `USE_SPECIFIC_API_FOR_WRITER=true` is required.
